config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}

  resources :tokens, except: [:show]

  root to: "home#index"
end

app/models/token.rb
class Token < ActiveRecord::Base
  belongs_to :user

  before_validation :normalize_secret

  validates :name, :secret, presence: true
  validate :secret_is_valid_base32

  scope :by_created_at, -> { order(:created_at) }

  def code
    ROTP::TOTP.new(secret).now
  end

  private

  def secret_is_valid_base32
    code if secret
  rescue ROTP::Base32::Base32Error
    errors.add :secret, "is not a valid base32 secret"
  end

  def normalize_secret
    secret&.delete!(" ")
  end
end

app/models/token_decorator.rb
class TokenDecorator < SimpleDelegator
  def code
    super.gsub(/(\d{3})(\d{3})/, '\1 \2')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :tokens
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to tokens_path if current_user
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :authenticate_user!

  respond_to :html

  def index
    @tokens = current_user
      .tokens
      .by_created_at
      .map { |t| TokenDecorator.new(t) }
  end

  def new
    @token = current_user.tokens.new
  end

  def create
    @token = current_user.tokens.create(token_params)
    flash[:notice] = "#{@token.name} created successfully" if @token.errors.blank?
    respond_with @token, location: tokens_path
  end

  def edit
    @token = token
  end

  def update
    @token = token
    @token.update(token_params)
    flash[:notice] = "#{@token.name} updated successfully"
    respond_with @token, location: tokens_path
  end

  def destroy
    @token = token
    @token.destroy
    flash[:notice] = "Token deleted successfully"
    respond_with @token
  end

  private

  def token
    current_user.tokens.find(params[:id])
  end

  def token_params
    params.require(:token).permit(:name, :secret)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.product-info
  %h1 Tokenator
  %p
    One-Time Password Generator (like Google Authenticator) on the web.

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == 'notice' ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Tokenator", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Tokenator"
      %meta{:content => content_for?(:description) ? yield(:description) : "Tokenator", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/tokens/_form.html.haml
= simple_form_for @token do |f|
  = f.input :name
  = f.input :secret if f.object.new_record?
  = f.button :submit, :class => 'btn btn-primary'
  = link_to 'Cancel', tokens_path, :class => 'btn'

app/views/tokens/edit.html.haml
%h3 Edit #{@token.name}
= render 'form'

app/views/tokens/index.html.haml
%h1 Tokens
%p
  = link_to new_token_path, :class => 'btn btn-primary  ' do
    %i.icon-plus.icon-white
    Add Token
%table.tokens
  %tr
    %th Token
    %th Temporary Code
    %th
  %tbody
    - @tokens.each do |token|
      %tr
        %td= token.name
        %td
          %strong= token.code
        %td
          .btn-group
            = link_to edit_token_path(token), :class => 'btn' do
              %i.icon-edit
              Edit
            = link_to token_path(token),
                      :method => :delete,
                      :data => { :confirm => "Are you sure you want to delete #{token.name}?" },
                      :class => 'btn btn-danger' do
              %i.icon-trash.icon-white
              Delete

app/views/tokens/new.html.haml
%h3 Create New Token
= render 'form'

app/views/tokens/show.html.haml
%h3= @token.name
%p
  Current Code:
  = @token.code
%p= link_to 'Edit Token', edit_token_path
%p= link_to 'Back to Tokens', tokens_path

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}